import Head from 'next/head'
// import Card from '../components/Card'
import Card from '../components/Card'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Stats preview card component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png"></link>
      </Head>
      <main className='relative bg-veryDarkBlue min-h-screen py-10 px-[5%] lg:py-[8%] lg:px-[10%]'>
        <Card/>
        <div className="absolute text-white attribution ml-5">
        Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank" rel="noreferrer">Frontend Mentor</a>. 
        Coded by <a href="#">Angel Murillo</a>.
      </div>
      </main>
    </div>
  )
}
